create table
    public."Category"
(
    id         bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name       character varying        not null default ''::character varying,
    constraint Category_pkey primary key (id)
) tablespace pg_default;


create table
    public."Subject"
(
    id         bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name       character varying        not null default ''::character varying,
    constraint Subject_pkey primary key (id)
) tablespace pg_default;


create table
    public."Student"
(
    id         bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    ldap_id    bigint null,
    constraint Student_pkey primary key (id)
) tablespace pg_default;


create table
    public."Teacher"
(
    id           bigint generated by default as identity,
    created_at   timestamp with time zone not null default now(),
    first_name   character varying null default ''::character varying,
    last_name    character varying null default ''::character varying,
    abbreviation character varying        not null default ''::character varying,
    constraint Teacher_pkey primary key (id)
) tablespace pg_default;


create table
    public."Workshop"
(
    id          bigint generated by default as identity,
    created_at  timestamp with time zone not null default now(),
    name        character varying        not null default ''::character varying,
    description character varying null default ''::character varying,
    startdate   timestamp without time zone not null,
    enddate     timestamp without time zone null,
    is_active   boolean                  not null,
    subject_id  bigint null,
    constraint Workshop_pkey primary key (id),
    constraint Workshop_subject_id_fkey foreign key (subject_id) references "Subject" (id) on update cascade on delete cascade
) tablespace pg_default;


create table
    public."Workshop_Category"
(
    created_at  timestamp with time zone not null default now(),
    workshop_id bigint                   not null,
    category_id bigint                   not null,
    constraint Workshop_Category_pkey primary key (workshop_id, category_id),
    constraint Workshop_Category_workshop_id_fkey foreign key (workshop_id) references "Workshop" (id) on update cascade on delete cascade,
    constraint Workshop_Category_category_id_fkey foreign key (category_id) references "Category" (id) on update cascade on delete cascade
) tablespace pg_default;

create table
    public."Subscription"
(
    created_at      timestamp with time zone not null default now(),
    workshop_id     bigint                   not null,
    subscription_id bigint                   not null,
    constraint Subscription_pkey primary key (workshop_id, subscription_id),
    constraint Subscription_workshop_id_fkey foreign key (workshop_id) references "Workshop" (id) on update cascade on delete cascade,
    constraint Subscription_student_id_fkey foreign key (subscription_id) references "Student" (id) on update cascade on delete cascade
) tablespace pg_default;


create table
    public."Workshop_Teacher"
(
    created_at  timestamp with time zone not null default now(),
    workshop_id bigint                   not null,
    teacher_id  bigint                   not null,
    constraint Workshop_Teacher_pkey primary key (workshop_id, teacher_id),
    constraint Workshop_Teacher_workshop_id_fkey foreign key (workshop_id) references "Workshop" (id) on update cascade on delete cascade,
    constraint Workshop_Teacher_teacher_id_fkey foreign key (teacher_id) references "Teacher" (id) on update cascade on delete cascade
) tablespace pg_default;